---
- hosts: jenkins
  connection: local
  become: True

  vars_files:
    #- 'local_settings.yml'
    - './vars/users.yaml'

  roles:
    - role: docker
    - role: jenkins
    - role: aws
    - role: terraform

